export const AUDIT_LOGS_ENTITY_TYPE = Object.freeze({
    USER: 'USER',
    DEPARTMENT: 'DEPARTMENT',
    DOCUMENT: 'DOCUMENT',
    DOCUMENT_VERSION: 'DOCUMENT_VERSION',
    DOCUMENT_SHARE: 'DOCUMENT_SHARE',
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
    COORDINATOR_REQUEST: 'COORDINATOR_REQUEST',
});

export const AUDIT_LOGS_ACTION = Object.freeze({
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SUSPENDED: 'SUSPENDED',
    PUBLISHED: 'PUBLISHED',
    UPLOADED: 'UPLOADED',
});
