export const DOCUMENTS_STATUS = Object.freeze({
    UPLOADED: 'UPLOADED',
    PENDING_OFFICER: 'PENDING_OFFICER',
    PENDING_DIRECTOR: 'PENDING_DIRECTOR',
    PUBLISHED: 'PUBLISHED',
    ATTACHMENT: 'ATTACHMENT',
});

export const DOCUMENT_REQUESTS_STATUS = Object.freeze({
    OPEN: 'OPEN',
    RESOLVED: 'RESOLVED',
    REJECTED: 'REJECTED',
});
