export const NOTIFICATIONS_ENTITY_TYPE = Object.freeze({
    DOCUMENT: 'DOCUMENT',
    COORDINATOR_REQUEST: 'COORDINATOR_REQUEST',
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
});

export const NOTIFICATIONS_ACTION = Object.freeze({
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    UPLOADED: 'UPLOADED',
    PUBLISHED: 'PUBLISHED',
    RESOLVED: 'RESOLVED',
    COMMENTED: 'COMMENTED',
});
