export const NOTIFICATIONS_ENTITY_TYPE = Object.freeze({
    DOCUMENT: 'DOCUMENT',
    COORDINATOR_REQUEST: 'COORDINATOR_REQUEST',
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
});

export const NOTIFICATIONS_ACTION = Object.freeze({
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    UNAPPROVED: 'UNAPPROVED',
    REJECTED: 'REJECTED',
    STASHED: 'STASHED',
    UPLOADED: 'UPLOADED',
    SHARED: 'SHARED',
    UNSHARED: 'UNSHARED',
    PUBLISHED: 'PUBLISHED',
    UNPUBLISHED: 'UNPUBLISHED',
    ARCHIVED: 'ARCHIVED',
    UNARCHIVED: 'UNARCHIVED',
    RESOLVED: 'RESOLVED',
    COMMENTED: 'COMMENTED',
    ATTACHED: 'ATTACHED',
    SUSPENDED: 'SUSPENDED',
    UNSUSPENDED: 'UNSUSPENDED',
    REVERTED: 'REVERTED',
});
